# Generated by Django 4.1.3 on 2022-11-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
