# Generated by Django 4.1.3 on 2022-11-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
